version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: pom_postgres_db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cornal_pom_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  neo4j:
    image: neo4j:5.13
    container_name: pom_neo4j_container
    restart: always
    environment:
      NEO4J_AUTH: neo4j/admin1234A # format: username/password
      NEO4J_dbms_security_procedures_unrestricted: gds.*
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 1G
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  mongodb:
    image: mongo:6
    container_name: pom_audit_db_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin1234A
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: pom_kafka_container
    restart: always
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: pom_zookeeper_container
    restart: always
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_logs:/var/lib/zookeeper/log
  eventstore:
    image: eventstore/eventstore:21.10.0-buster-slim
    container_name: pom_eventstore_container
    restart: always
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_MEM_DB=false
      - EVENTSTORE_CLUSTER_SIZE=1
    ports:
      - '2113:2113' # HTTP interface (management UI, admin API)
      - '1113:1113' # TCP interface (for clients)
    volumes:
      - eventstore_data:/var/lib/eventstore

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
  mongodb_data:
  kafka_data:
  zookeeper_data:
  zookeeper_logs:
  eventstore_data:
